// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcYBUofxEBciZhJuMMMDYVBDtGgd3KsJs',
    appId: '1:684021401306:web:f6a659bed63c0e36b907e3',
    messagingSenderId: '684021401306',
    projectId: 'my-notes-flutter-project-45bf8',
    authDomain: 'my-notes-flutter-project-45bf8.firebaseapp.com',
    storageBucket: 'my-notes-flutter-project-45bf8.appspot.com',
    measurementId: 'G-G4JB1G66LW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAClCg3WKsdaekm0j-58JsUa8_yeo_jMFA',
    appId: '1:684021401306:android:fe4c33df128c96a4b907e3',
    messagingSenderId: '684021401306',
    projectId: 'my-notes-flutter-project-45bf8',
    storageBucket: 'my-notes-flutter-project-45bf8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8A3C_94UftjK2SV4QZsl3X3_2xkIc8QA',
    appId: '1:684021401306:ios:8ad12c0aed78ce3eb907e3',
    messagingSenderId: '684021401306',
    projectId: 'my-notes-flutter-project-45bf8',
    storageBucket: 'my-notes-flutter-project-45bf8.appspot.com',
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8A3C_94UftjK2SV4QZsl3X3_2xkIc8QA',
    appId: '1:684021401306:ios:3120ea2f3ba9c08ab907e3',
    messagingSenderId: '684021401306',
    projectId: 'my-notes-flutter-project-45bf8',
    storageBucket: 'my-notes-flutter-project-45bf8.appspot.com',
    iosBundleId: 'com.example.untitled.RunnerTests',
  );
}
